"use client";
import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import Moveable from "react-moveable";
import Selecto from "react-selecto";
import AdminFilePicker from "@/components/admin/AdminFilePicker";
import { imageFileToDataUrl } from "@/lib/page-content";
import { clonePage, cryptoId, defaultLayout, type EditorMode, type VisualDocument, type VisualElement, type VisualElementType } from "@/lib/visual-editor";
import { showAdminToast } from "@/lib/admin-toast";

type Props={value:VisualDocument;onChange:(value:VisualDocument)=>void;label:string};
type History={past:VisualDocument[];future:VisualDocument[]};
const copy=<T,>(v:T):T=>structuredClone(v);

export default function VisualPageEditor({value,onChange,label}:Props){
 const [mode,setMode]=useState<EditorMode>("desktop");
 const [pageIndex,setPageIndex]=useState(0); const [selected,setSelected]=useState<string[]>([]); const [grid,setGrid]=useState(true); const [zoom,setZoom]=useState(.62);
 const [history,setHistory]=useState<History>({past:[],future:[]}); const canvasRefs=useRef<Record<string,HTMLDivElement|null>>({}); const gestureStart=useRef<VisualDocument|null>(null);
 const page=value.pages[Math.min(pageIndex,value.pages.length-1)] || value.pages[0]; const pageSize=page ? page[mode] : {width:1420,height:1000};
 const selectedEls=page?.elements.filter(e=>selected.includes(e.id))||[];
 const currentCanvas=page?canvasRefs.current[page.id]:null;
 const targets=selected.map((id:string)=>currentCanvas?.querySelector(`[data-element-id="${id}"]`) as HTMLElement|null).filter(Boolean) as HTMLElement[];
 const guidelines=page?.elements.filter(e=>!selected.includes(e.id)).map(e=>currentCanvas?.querySelector(`[data-element-id="${e.id}"]`) as HTMLElement|null).filter(Boolean) as HTMLElement[];

 const commit=useCallback((next:VisualDocument,record=true)=>{if(record)setHistory(h=>({past:[...h.past.slice(-39),copy(value)],future:[]}));onChange(next)},[onChange,value]);
 const updatePage=(fn:(p:typeof page)=>typeof page,record=true)=>{const next=copy(value);next.pages[pageIndex]=fn(next.pages[pageIndex]);commit(next,record)};
 const undo=()=>setHistory(h=>{const prev=h.past.at(-1);if(!prev)return h;onChange(copy(prev));return {past:h.past.slice(0,-1),future:[copy(value),...h.future]}});
 const redo=()=>setHistory(h=>{const next=h.future[0];if(!next)return h;onChange(copy(next));return {past:[...h.past,copy(value)],future:h.future.slice(1)}});

 useEffect(()=>{setSelected([])},[mode,pageIndex]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()} if((e.key==="Delete"||e.key==="Backspace")&&!((e.target as HTMLElement)?.matches("input,textarea"))){e.preventDefault();removeSelected()}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)});

 const addElement=(type:VisualElementType)=>{const desktop=defaultLayout(type,"desktop"),mobile=defaultLayout(type,"mobile"); const el:VisualElement={id:cryptoId(type),type,layouts:{desktop,mobile},opacity:1};
  if(type==="text")Object.assign(el,{text:"새 텍스트",fontSize:36,fontWeight:400,color:"#2f2a26",textAlign:"left",lineHeight:1.45});
  if(type==="rect")Object.assign(el,{background:"#ffffff",borderColor:"#9b8c80",borderWidth:1,radius:0});
  if(type==="line")Object.assign(el,{lineOrientation:"horizontal",color:"#9b8c80",borderWidth:1});
  updatePage(p=>({...p,elements:[...p.elements,el]}));setSelected([el.id]);
 };
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const src=await imageFileToDataUrl(file);const desktop=defaultLayout("image","desktop"),mobile=defaultLayout("image","mobile");const el:VisualElement={id:cryptoId("image"),type:"image",src,objectFit:"cover",opacity:1,layouts:{desktop,mobile}};updatePage(p=>({...p,elements:[...p.elements,el]}));setSelected([el.id]);showAdminToast("이미지가 추가되었습니다. 저장 시 R2에 최적화 이미지가 저장됩니다.","success")}catch(err){showAdminToast(err instanceof Error?err.message:"이미지 처리 실패","error")}};
 const removeSelected=()=>{if(!selected.length)return;updatePage(p=>({...p,elements:p.elements.filter(e=>!selected.includes(e.id))}));setSelected([])};
 const duplicateSelected=()=>{if(!selectedEls.length)return;const copies=selectedEls.map(el=>{const n=copy(el);n.id=cryptoId(el.type);(["desktop","mobile"] as EditorMode[]).forEach(m=>{n.layouts[m].x+=18;n.layouts[m].y+=18;n.layouts[m].z+=1});return n});updatePage(p=>({...p,elements:[...p.elements,...copies]}));setSelected(copies.map(e=>e.id))};
 const layer=(where:"front"|"back")=>{if(!selected.length)return;const zs=page.elements.map(e=>e.layouts[mode].z);const z=where==="front"?Math.max(0,...zs)+1:Math.min(0,...zs)-1;updatePage(p=>({...p,elements:p.elements.map(e=>selected.includes(e.id)?{...e,layouts:{...e.layouts,[mode]:{...e.layouts[mode],z}}}:e)}))};
 const addPage=()=>{const next=copy(value);const width=Math.max(640,window.innerWidth-500),height=Math.max(640,window.innerHeight);next.pages.push({id:cryptoId("page"),name:`${next.pages.length+1} PAGE`,desktop:{width,height},mobile:{width:390,height:693},elements:[]});commit(next);setPageIndex(next.pages.length-1)};
 const duplicatePage=()=>{const next=copy(value);const dup=clonePage(next.pages[pageIndex]);dup.name=`${pageIndex+2} PAGE`;next.pages.splice(pageIndex+1,0,dup);next.pages.forEach((p,i)=>p.name=`${i+1} PAGE`);commit(next);setPageIndex(pageIndex+1)};
 const deletePage=()=>{if(value.pages.length===1){showAdminToast("마지막 페이지는 삭제할 수 없습니다.","error");return}if(!confirm("현재 페이지 전체를 삭제할까요?"))return;const next=copy(value);next.pages.splice(pageIndex,1);next.pages.forEach((p,i)=>p.name=`${i+1} PAGE`);commit(next);setPageIndex(Math.max(0,pageIndex-1))};
 const movePage=(from:number,to:number)=>{if(from===to||to<0||to>=value.pages.length)return;const next=copy(value);const [p]=next.pages.splice(from,1);next.pages.splice(to,0,p);next.pages.forEach((x,i)=>x.name=`${i+1} PAGE`);commit(next);setPageIndex(to)};
 const fitCurrent=()=>{const next=copy(value);if(mode==="desktop")next.pages[pageIndex].desktop={width:Math.max(640,window.innerWidth-500),height:Math.max(640,window.innerHeight)};else next.pages[pageIndex].mobile={width:390,height:693};commit(next)};
 const patchSelected=(patch:Partial<VisualElement>)=>updatePage(p=>({...p,elements:p.elements.map(e=>selected.includes(e.id)?{...e,...patch}:e)}));

 const begin=()=>{gestureStart.current=copy(value)}; const finish=()=>{if(gestureStart.current)setHistory(h=>({past:[...h.past.slice(-39),gestureStart.current!],future:[]}));gestureStart.current=null};
 const mutateLayout=(id:string,patch:Partial<VisualElement["layouts"][EditorMode]>)=>{const next=copy(value);const el=next.pages[pageIndex].elements.find(e=>e.id===id);if(el)el.layouts[mode]={...el.layouts[mode],...patch};onChange(next)};

 if(!page)return null; const scale=zoom; const width=pageSize.width*scale,height=pageSize.height*scale;
 return <div className="lite-editor">
  <header className="lite-editor-topbar"><strong>{label} 디자인 편집기</strong><div className="lite-mode"><button type="button" className={mode==="desktop"?"active":""} onClick={()=>setMode("desktop")}>Desktop</button><button type="button" className={mode==="mobile"?"active":""} onClick={()=>setMode("mobile")}>Mobile 390px</button></div><button type="button" onClick={undo} disabled={!history.past.length}>↶</button><button type="button" onClick={redo} disabled={!history.future.length}>↷</button><button type="button" className={grid?"active":""} onClick={()=>setGrid(v=>!v)}>Grid</button><button type="button" onClick={fitCurrent}>현재 화면 비율</button><label>Zoom <input type="range" min=".3" max="1" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></header>
  <div className="lite-editor-body">
   <aside className="lite-tools"><button type="button" onClick={()=>addElement("text")}><b>T</b><span>Text</span></button><label className="lite-tool-upload"><b>▧</b><span>Image</span><AdminFilePicker onChange={upload} help=""/></label><button type="button" onClick={()=>addElement("rect")}><b>□</b><span>Box</span></button><button type="button" onClick={()=>addElement("line")}><b>—</b><span>Line</span></button><button type="button" onClick={()=>layer("front")}><b>⇧</b><span>Front</span></button><button type="button" onClick={()=>layer("back")}><b>⇩</b><span>Back</span></button><button type="button" onClick={duplicateSelected} disabled={!selected.length}><b>⧉</b><span>Copy</span></button><button type="button" onClick={removeSelected} disabled={!selected.length}><b>⌫</b><span>Delete</span></button></aside>
   <main className="lite-workspace"><div className={`lite-page-stack ${grid?"show-stack-grid":""}`} style={{["--grid-step" as string]:`${50*scale}px`}}>{value.pages.map((stackPage,stackIndex)=>{const stackSize=stackPage[mode];const stackWidth=stackSize.width*scale,stackHeight=stackSize.height*scale;return <section key={stackPage.id} className={`lite-stack-page ${stackIndex===pageIndex?"active":""}`} style={{width:stackWidth}} onMouseDown={()=>{if(stackIndex!==pageIndex){setPageIndex(stackIndex);setSelected([])}}}><div className="lite-stack-page-label">{stackIndex+1} PAGE</div><div className={`lite-canvas-wrap ${grid?"show-grid":""}`} style={{width:stackWidth,height:stackHeight}}><div ref={node=>{canvasRefs.current[stackPage.id]=node}} className="lite-canvas" style={{width:stackSize.width,height:stackSize.height,transform:`scale(${scale})`,transformOrigin:"top left"}}>
    <div className="lite-grid-overlay"/>
    {stackPage.elements.map(el=>{const l=el.layouts[mode];return <div key={el.id} data-element-id={el.id} className={`lite-element lite-${el.type}`} style={{left:l.x,top:l.y,width:l.width,height:l.height,transform:`rotate(${l.rotate}deg)`,zIndex:l.z,opacity:el.opacity??1}} onMouseDown={e=>{e.stopPropagation();if(stackIndex!==pageIndex)setPageIndex(stackIndex);if(!e.shiftKey)setSelected([el.id]);else setSelected((ids:string[])=>ids.includes(el.id)?ids.filter((x:string)=>x!==el.id):[...ids,el.id])}}>
      {el.type==="text"?<div style={{fontSize:el.fontSize,fontWeight:el.fontWeight,color:el.color,textAlign:el.textAlign,lineHeight:el.lineHeight,whiteSpace:"pre-wrap"}}>{el.text}</div>:null}
      {el.type==="image"?<img src={el.src||""} alt="" draggable={false} style={{width:"100%",height:"100%",objectFit:el.objectFit||"cover"}}/>:null}
      {el.type==="rect"?<div style={{width:"100%",height:"100%",boxSizing:"border-box",background:el.background,border:`${el.borderWidth}px solid ${el.borderColor}`,borderRadius:el.radius}}/>:null}
      {el.type==="line"?<div style={{width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><i style={{display:"block",background:el.color,width:el.lineOrientation==="vertical"?el.borderWidth:"100%",height:el.lineOrientation==="vertical"?"100%":el.borderWidth}}/></div>:null}
    </div>})}
    {stackIndex===pageIndex?<><Moveable target={targets.length===1?targets[0]:targets} draggable resizable rotatable snappable snapGap snapThreshold={7} elementGuidelines={guidelines} verticalGuidelines={[0,pageSize.width/2,pageSize.width]} horizontalGuidelines={[0,pageSize.height/2,pageSize.height]} bounds={{left:0,top:0,right:pageSize.width,bottom:pageSize.height}} onDragStart={begin} onDrag={({target,left,top}:any)=>{const id=(target as HTMLElement).dataset.elementId;if(id)mutateLayout(id,{x:left,y:top})}} onDragEnd={finish} onDragGroupStart={begin} onDragGroup={({events}:any)=>events.forEach((ev:any)=>{const id=(ev.target as HTMLElement).dataset.elementId;if(id)mutateLayout(id,{x:ev.left,y:ev.top})})} onDragGroupEnd={finish} onResizeStart={begin} onResize={({target,width,height,drag}:any)=>{const id=(target as HTMLElement).dataset.elementId;if(id)mutateLayout(id,{width,height,x:drag.left,y:drag.top})}} onResizeEnd={finish} onResizeGroupStart={begin} onResizeGroup={({events}:any)=>events.forEach((ev:any)=>{const id=(ev.target as HTMLElement).dataset.elementId;if(id)mutateLayout(id,{width:ev.width,height:ev.height,x:ev.drag.left,y:ev.drag.top})})} onResizeGroupEnd={finish} onRotateStart={begin} onRotate={({target,rotation}:any)=>{const id=(target as HTMLElement).dataset.elementId;if(id)mutateLayout(id,{rotate:rotation})}} onRotateEnd={finish} onRotateGroupStart={begin} onRotateGroup={({events}:any)=>events.forEach((ev:any)=>{const id=(ev.target as HTMLElement).dataset.elementId;if(id)mutateLayout(id,{rotate:ev.rotation})})} onRotateGroupEnd={finish}/>
    <Selecto dragContainer={currentCanvas||undefined} selectableTargets={[".lite-stack-page.active .lite-element"]} hitRate={20} selectByClick selectFromInside={false} toggleContinueSelect={["shift"]} ratio={0} onSelectEnd={(e:any)=>setSelected(e.selected.map((x:Element)=>(x as HTMLElement).dataset.elementId||"").filter(Boolean))}/></>:null}
   </div></div></section>})}</div></main>
   <aside className="lite-inspector"><h3>Properties</h3>{selectedEls.length===1?<Properties element={selectedEls[0]} onPatch={patchSelected}/>:<p>{selectedEls.length?`${selectedEls.length}개 선택됨`:"요소를 선택하세요."}</p>}<h3>Layers</h3><div className="lite-layer-list">{[...page.elements].sort((a,b)=>b.layouts[mode].z-a.layouts[mode].z).map(el=><button type="button" key={el.id} className={selected.includes(el.id)?"active":""} onClick={()=>setSelected([el.id])}><span>{el.type}</span><small>{el.type==="text"?el.text?.slice(0,18):el.id.slice(-6)}</small></button>)}</div></aside>
  </div>
  <footer className="lite-pages"><div className="lite-page-strip">{value.pages.map((p,i)=><div key={p.id} className={`lite-page-thumb ${i===pageIndex?"active":""}`}><button type="button" onClick={()=>{setPageIndex(i);setSelected([]);requestAnimationFrame(()=>canvasRefs.current[p.id]?.closest(".lite-stack-page")?.scrollIntoView({behavior:"smooth",block:"center"}))}}><div className="lite-thumb-preview">{p.elements.slice(0,18).map(el=>{const l=el.layouts[mode],sz=p[mode];return <i key={el.id} className={`t-${el.type}`} style={{left:`${l.x/sz.width*100}%`,top:`${l.y/sz.height*100}%`,width:`${Math.max(2,l.width/sz.width*100)}%`,height:`${Math.max(2,l.height/sz.height*100)}%`,background:el.type==="image"?"#c7d5df":el.type==="text"?"#777":el.type==="rect"?(el.background||"#eee"):(el.color||"#aaa")}}/>})}</div><span>{i+1}</span><small>{p.elements.length} elements</small></button><div><button type="button" onClick={()=>movePage(i,i-1)}>←</button><button type="button" onClick={()=>movePage(i,i+1)}>→</button></div></div>)}<button type="button" className="lite-add-page" onClick={addPage}>＋ 페이지 추가</button></div><div className="lite-page-actions"><button type="button" onClick={duplicatePage}>페이지 복제</button><button type="button" onClick={deletePage}>페이지 삭제</button></div></footer>
 </div>
}

function Properties({element,onPatch}:{element:VisualElement;onPatch:(p:Partial<VisualElement>)=>void}){
 return <div className="lite-properties">
  {element.type==="text"?<><label>Text<textarea value={element.text||""} onChange={e=>onPatch({text:e.target.value})}/></label><label>Size<input type="number" value={element.fontSize||36} onChange={e=>onPatch({fontSize:Number(e.target.value)})}/></label><label>Weight<select value={element.fontWeight||400} onChange={e=>onPatch({fontWeight:Number(e.target.value)})}><option value="300">Light</option><option value="400">Regular</option><option value="500">Medium</option><option value="700">Bold</option></select></label><label>Color<input type="color" value={element.color||"#2f2a26"} onChange={e=>onPatch({color:e.target.value})}/></label><label>Align<select value={element.textAlign||"left"} onChange={e=>onPatch({textAlign:e.target.value as VisualElement["textAlign"]})}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></>:null}
  {element.type==="image"?<label>Fit<select value={element.objectFit||"cover"} onChange={e=>onPatch({objectFit:e.target.value as "cover"|"contain"})}><option value="cover">Cover</option><option value="contain">Contain</option></select></label>:null}
  {element.type==="rect"?<><label>Fill<input type="color" value={element.background||"#ffffff"} onChange={e=>onPatch({background:e.target.value})}/></label><label>Stroke<input type="color" value={element.borderColor||"#9b8c80"} onChange={e=>onPatch({borderColor:e.target.value})}/></label><label>Stroke px<input type="number" min="0" max="30" value={element.borderWidth||1} onChange={e=>onPatch({borderWidth:Number(e.target.value)})}/></label><label>Radius<input type="number" min="0" max="200" value={element.radius||0} onChange={e=>onPatch({radius:Number(e.target.value)})}/></label></>:null}
  {element.type==="line"?<><label>Color<input type="color" value={element.color||"#9b8c80"} onChange={e=>onPatch({color:e.target.value})}/></label><label>Thickness<input type="number" min="1" max="30" value={element.borderWidth||1} onChange={e=>onPatch({borderWidth:Number(e.target.value)})}/></label><label>Direction<select value={element.lineOrientation||"horizontal"} onChange={e=>onPatch({lineOrientation:e.target.value as "horizontal"|"vertical"})}><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label></>:null}
  <label>Opacity<input type="range" min="0" max="1" step=".05" value={element.opacity??1} onChange={e=>onPatch({opacity:Number(e.target.value)})}/></label>
 </div>
}
