"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { imageFileToDataUrl, type FabricDocument, type FabricPage, type FabricResponsiveDocument } from "@/lib/page-content";
import { showAdminToast } from "@/lib/admin-toast";

type Mode = "desktop" | "mobile";
type FabricRuntime = { canvas: any; fabric: any };
type Inspector = { pageId:string; object:any } | null;
type GuideState = { x:number[]; y:number[]; distances?:{left:number;right:number;top:number;bottom:number} };

type Props = { value?: FabricResponsiveDocument; onChange:(value:FabricResponsiveDocument)=>void; pageLabel:string };
const EMPTY_JSON = { version:"7.0.0", objects:[] };
const BLUE = "#28aaf7";
const GRID = 20;

function uid(prefix="page"){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function pageSize(mode:Mode){
  if(typeof window==="undefined") return mode==="mobile"?{width:390,height:844}:{width:1420,height:900};
  return mode==="mobile"?{width:390,height:Math.max(700,window.innerHeight)}:{width:Math.max(900,window.innerWidth-500),height:Math.max(700,window.innerHeight)};
}
function blankPage(mode:Mode):FabricPage{const size=pageSize(mode);return{id:uid(),...size,json:structuredClone(EMPTY_JSON)}}
function ensureDoc(doc:FabricDocument|undefined,mode:Mode):FabricDocument{return doc?.pages?.length?doc:{version:1,pages:[blankPage(mode)]}}
function cloneJson<T>(value:T):T{return JSON.parse(JSON.stringify(value))}
function getKind(obj:any){return obj?.data?.kind || (obj?.type==="i-text"?"text":obj?.type==="image"?"image":obj?.type||"object")}
function styleObject(obj:any){obj.set({borderColor:BLUE,cornerColor:"#fff",cornerStrokeColor:BLUE,cornerStyle:"rect",cornerSize:10,transparentCorners:false,padding:0});obj.setCoords?.();return obj}

function CanvasPage({page,grid,onReady,onChange,onSelect,onThumb}:{page:FabricPage;grid:boolean;onReady:(id:string,r:FabricRuntime|null)=>void;onChange:(id:string,json:any)=>void;onSelect:(inspector:Inspector)=>void;onThumb:(id:string,url:string)=>void}){
 const canvasRef=useRef<HTMLCanvasElement|null>(null); const hostRef=useRef<HTMLDivElement|null>(null); const runtime=useRef<FabricRuntime|null>(null); const [scale,setScale]=useState(1); const [guide,setGuide]=useState<GuideState|null>(null); const loading=useRef(true); const lastJson=useRef(JSON.stringify(page.json||EMPTY_JSON));
 useEffect(()=>{const host=hostRef.current;if(!host)return;const update=()=>setScale(Math.min(1,Math.max(.18,host.clientWidth/page.width)));update();const ro=new ResizeObserver(update);ro.observe(host);return()=>ro.disconnect()},[page.width]);
 useEffect(()=>{let dead=false; let canvas:any=null;
   (async()=>{const fabric=await import("fabric");if(dead||!canvasRef.current)return;canvas=new fabric.Canvas(canvasRef.current,{width:page.width,height:page.height,preserveObjectStacking:true,selection:true,backgroundColor:"#fff"});runtime.current={canvas,fabric};onReady(page.id,runtime.current);loading.current=true;await canvas.loadFromJSON(page.json||EMPTY_JSON);canvas.getObjects().forEach((o:any)=>styleObject(o));canvas.requestRenderAll();loading.current=false;
     const snapshot=()=>{if(loading.current)return;const json=canvas.toObject(["data"]);const raw=JSON.stringify(json);lastJson.current=raw;onChange(page.id,json);requestAnimationFrame(()=>{try{onThumb(page.id,canvas.toDataURL({format:"jpeg",quality:.55,multiplier:.12}))}catch{}})};
     const select=()=>{const obj=canvas.getActiveObject();onSelect(obj?{pageId:page.id,object:obj}:null)};
     const snapMove=(event:any)=>{const obj=event.target;if(!obj)return;let left=Number(obj.left||0),top=Number(obj.top||0);if(grid){left=Math.round(left/GRID)*GRID;top=Math.round(top/GRID)*GRID;obj.set({left,top})}
       const box=obj.getBoundingRect();const xs=[0,page.width/2,page.width],ys=[0,page.height/2,page.height];for(const other of canvas.getObjects()){if(other===obj||other.excludeFromExport)continue;const b=other.getBoundingRect();xs.push(b.left,b.left+b.width/2,b.left+b.width);ys.push(b.top,b.top+b.height/2,b.top+b.height)}
       const obx=[box.left,box.left+box.width/2,box.left+box.width],oby=[box.top,box.top+box.height/2,box.top+box.height];let gx:number[]=[];let gy:number[]=[];const threshold=8;
       for(const tx of xs){let best: number|null=null;for(const ox of obx){const diff=tx-ox;if(Math.abs(diff)<=threshold&&(best===null||Math.abs(diff)<Math.abs(best)))best=diff}if(best!==null){obj.set({left:Number(obj.left||0)+best});gx=[tx];break}}
       const box2=obj.getBoundingRect();const oby2=[box2.top,box2.top+box2.height/2,box2.top+box2.height];for(const ty of ys){let best:number|null=null;for(const oy of oby2){const diff=ty-oy;if(Math.abs(diff)<=threshold&&(best===null||Math.abs(diff)<Math.abs(best)))best=diff}if(best!==null){obj.set({top:Number(obj.top||0)+best});gy=[ty];break}}
       obj.setCoords();const b3=obj.getBoundingRect();setGuide({x:gx,y:gy,distances:{left:Math.round(b3.left),right:Math.round(page.width-(b3.left+b3.width)),top:Math.round(b3.top),bottom:Math.round(page.height-(b3.top+b3.height))}});canvas.requestRenderAll();
     };
     canvas.on("selection:created",select);canvas.on("selection:updated",select);canvas.on("selection:cleared",()=>onSelect(null));canvas.on("object:moving",snapMove);canvas.on("object:scaling",(e:any)=>snapMove(e));canvas.on("object:rotating",()=>setGuide(null));canvas.on("object:modified",()=>{setGuide(null);snapshot();select()});canvas.on("object:added",snapshot);canvas.on("object:removed",snapshot);
     requestAnimationFrame(()=>{try{onThumb(page.id,canvas.toDataURL({format:"jpeg",quality:.55,multiplier:.12}))}catch{}})
   })();
   return()=>{dead=true;onReady(page.id,null);runtime.current=null;canvas?.dispose?.()}
 },[page.id,page.width,page.height,grid]);
 useEffect(()=>{const r=runtime.current;if(!r||loading.current)return;const raw=JSON.stringify(page.json||EMPTY_JSON);if(raw===lastJson.current)return;loading.current=true;void r.canvas.loadFromJSON(page.json||EMPTY_JSON).then(()=>{r.canvas.getObjects().forEach((o:any)=>styleObject(o));lastJson.current=raw;loading.current=false;r.canvas.requestRenderAll();requestAnimationFrame(()=>{try{onThumb(page.id,r.canvas.toDataURL({format:"jpeg",quality:.55,multiplier:.12}))}catch{}})})},[page.json]);
 return <div ref={hostRef} className="fabric-page-host"><div className="fabric-page-scaled" style={{width:page.width*scale,height:page.height*scale}}><div className={`fabric-page-inner ${grid?"is-grid":""}`} style={{width:page.width,height:page.height,transform:`scale(${scale})`}}><div className="fabric-ruler fabric-ruler-x"/><div className="fabric-ruler fabric-ruler-y"/><canvas ref={canvasRef}/>{guide&&<GuideOverlay page={page} guide={guide}/>}</div></div></div>
}

export default function FabricDesigner({value,onChange,pageLabel}:Props){
 const [mode,setMode]=useState<Mode>("desktop"); const [grid,setGrid]=useState(true); const [activePage,setActivePage]=useState(""); const [inspector,setInspector]=useState<Inspector>(null); const [thumbs,setThumbs]=useState<Record<string,string>>({}); const runtime=useRef<Record<string,FabricRuntime>>({}); const fileRef=useRef<HTMLInputElement|null>(null); const history=useRef<FabricResponsiveDocument[]>([]); const future=useRef<FabricResponsiveDocument[]>([]); const skipHistory=useRef(false);
 const normalized=useMemo(()=>({desktop:ensureDoc(value?.desktop,"desktop"),mobile:ensureDoc(value?.mobile,"mobile")}),[value]); const doc=normalized[mode]; const pageId=activePage&&doc.pages.some(p=>p.id===activePage)?activePage:doc.pages[0]?.id||"";
 useEffect(()=>{if(!activePage&&doc.pages[0])setActivePage(doc.pages[0].id)},[mode,doc.pages.length]);
 const commit=(next:FabricResponsiveDocument,record=true)=>{if(record&&!skipHistory.current){history.current.push(cloneJson(normalized));if(history.current.length>40)history.current.shift();future.current=[]}onChange(next)};
 const updateDoc=(nextDoc:FabricDocument,record=true)=>commit({...normalized,[mode]:nextDoc},record);
 const updatePageJson=(id:string,json:any)=>{const next={...doc,pages:doc.pages.map(p=>p.id===id?{...p,json}:p)};commit({...normalized,[mode]:next},true)};
 const pageRuntime=()=>runtime.current[pageId];
 const addObject=(obj:any)=>{const r=pageRuntime();if(!r)return;styleObject(obj);r.canvas.add(obj);r.canvas.setActiveObject(obj);r.canvas.centerObject(obj);r.canvas.requestRenderAll()};
 const addText=()=>{const r=pageRuntime();if(!r)return;const obj=new r.fabric.IText("텍스트를 입력하세요",{left:80,top:80,fontSize:32,fontFamily:"Arial",fill:"#3d2b20",data:{kind:"text"}});addObject(obj)};
 const addRect=()=>{const r=pageRuntime();if(!r)return;addObject(new r.fabric.Rect({left:100,top:100,width:320,height:180,fill:"#ffffff",stroke:"#6c625c",strokeWidth:1,data:{kind:"rect"}}))};
 const addHLine=()=>{const r=pageRuntime();if(!r)return;addObject(new r.fabric.Rect({left:100,top:180,width:360,height:2,fill:"#6c625c",strokeWidth:0,data:{kind:"hline"},lockScalingY:false}))};
 const addVLine=()=>{const r=pageRuntime();if(!r)return;addObject(new r.fabric.Rect({left:200,top:100,width:2,height:360,fill:"#6c625c",strokeWidth:0,data:{kind:"vline"},lockScalingX:false}))};
 const addImage=()=>fileRef.current?.click();
 const onFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;try{const src=await imageFileToDataUrl(file);const r=pageRuntime();if(!r)return;const img=await r.fabric.FabricImage.fromURL(src);img.set({left:120,top:120,data:{kind:"image"}});const max=Math.min(720,doc.pages.find(p=>p.id===pageId)?.width||720);if(img.width>max)img.scaleToWidth(max);addObject(img)}catch(err){showAdminToast(err instanceof Error?err.message:"이미지 처리 실패","error")}};
 const duplicate=()=>{const r=pageRuntime();const obj=r?.canvas.getActiveObject();if(!r||!obj)return;void obj.clone(["data"]).then((cl:any)=>{cl.set({left:Number(cl.left||0)+24,top:Number(cl.top||0)+24});styleObject(cl);r.canvas.add(cl);r.canvas.setActiveObject(cl);r.canvas.requestRenderAll()})};
 const remove=()=>{const r=pageRuntime();const obj=r?.canvas.getActiveObject();if(!r||!obj)return;if(obj.type==="activeSelection")obj.getObjects().forEach((o:any)=>r.canvas.remove(o));else r.canvas.remove(obj);r.canvas.discardActiveObject();r.canvas.requestRenderAll();setInspector(null)};
 const layer=(action:"front"|"forward"|"backward"|"back")=>{const r=pageRuntime();const obj=r?.canvas.getActiveObject();if(!r||!obj)return;({front:()=>r.canvas.bringObjectToFront(obj),forward:()=>r.canvas.bringObjectForward(obj),backward:()=>r.canvas.sendObjectBackwards(obj),back:()=>r.canvas.sendObjectToBack(obj)})[action]();r.canvas.requestRenderAll();updatePageJson(pageId,r.canvas.toObject(["data"]))};
 const setProp=(key:string,val:any)=>{const r=pageRuntime();const obj=r?.canvas.getActiveObject();if(!r||!obj)return;obj.set(key,val);obj.setCoords();r.canvas.requestRenderAll();setInspector({pageId,object:obj});updatePageJson(pageId,r.canvas.toObject(["data"]))};
 const addPage=()=>{const p=blankPage(mode);updateDoc({...doc,pages:[...doc.pages,p]});setActivePage(p.id);requestAnimationFrame(()=>document.getElementById(`fabric-page-${p.id}`)?.scrollIntoView({behavior:"smooth",block:"center"}))};
 const dupPage=()=>{const idx=doc.pages.findIndex(p=>p.id===pageId);if(idx<0)return;const src=doc.pages[idx];const cp={...cloneJson(src),id:uid(),json:cloneJson(src.json)};const pages=[...doc.pages];pages.splice(idx+1,0,cp);updateDoc({...doc,pages});setActivePage(cp.id)};
 const deletePage=()=>{if(doc.pages.length<=1){showAdminToast("마지막 페이지는 삭제할 수 없습니다.","error");return}if(!confirm("현재 페이지를 삭제할까요?"))return;const idx=doc.pages.findIndex(p=>p.id===pageId);const pages=doc.pages.filter(p=>p.id!==pageId);updateDoc({...doc,pages});setActivePage(pages[Math.max(0,idx-1)]?.id||pages[0].id)};
 const movePage=(dir:-1|1)=>{const idx=doc.pages.findIndex(p=>p.id===pageId);const t=idx+dir;if(idx<0||t<0||t>=doc.pages.length)return;const pages=[...doc.pages];[pages[idx],pages[t]]=[pages[t],pages[idx]];updateDoc({...doc,pages})};
 const resizeCurrent=()=>{const p=doc.pages.find(p=>p.id===pageId);const r=pageRuntime();if(!p||!r)return;const size=pageSize(mode),sx=size.width/p.width,sy=size.height/p.height;r.canvas.getObjects().forEach((o:any)=>{o.set({left:Number(o.left||0)*sx,top:Number(o.top||0)*sy,scaleX:Number(o.scaleX||1)*sx,scaleY:Number(o.scaleY||1)*sy});o.setCoords()});const json=r.canvas.toObject(["data"]);updateDoc({...doc,pages:doc.pages.map(x=>x.id===p.id?{...x,...size,json}:x)})};
 const undo=()=>{const prev=history.current.pop();if(!prev)return;future.current.push(cloneJson(normalized));skipHistory.current=true;onChange(prev);setTimeout(()=>{skipHistory.current=false},0)}; const redo=()=>{const next=future.current.pop();if(!next)return;history.current.push(cloneJson(normalized));skipHistory.current=true;onChange(next);setTimeout(()=>{skipHistory.current=false},0)};
 const selected=inspector?.object;const kind=getKind(selected);
 return <section className="fabric-editor-shell">
  <input ref={fileRef} type="file" accept="image/*" hidden onChange={onFile}/>
  <header className="fabric-editor-top"><strong>{pageLabel} 디자인 편집기</strong><div className="fabric-mode"><button type="button" className={mode==="desktop"?"is-active":""} onClick={()=>{setMode("desktop");setInspector(null);setActivePage("")}}>Desktop</button><button type="button" className={mode==="mobile"?"is-active":""} onClick={()=>{setMode("mobile");setInspector(null);setActivePage("")}}>Mobile</button></div><button type="button" onClick={undo} disabled={!history.current.length}>↶ Undo</button><button type="button" onClick={redo} disabled={!future.current.length}>↷ Redo</button><button type="button" className={grid?"is-active":""} onClick={()=>setGrid(v=>!v)}>Grid {grid?"ON":"OFF"}</button><button type="button" onClick={resizeCurrent}>현재 화면 비율로 맞춤</button></header>
  <div className="fabric-editor-main">
   <aside className="fabric-tools"><button type="button" onClick={addText}><b>T</b><span>텍스트</span></button><button type="button" onClick={addImage}><b>▧</b><span>이미지</span></button><button type="button" onClick={addRect}><b>□</b><span>사각형</span></button><button type="button" onClick={addHLine}><b>━</b><span>가로선</span></button><button type="button" onClick={addVLine}><b>┃</b><span>세로선</span></button><button type="button" onClick={duplicate}><b>⧉</b><span>복제</span></button><button type="button" onClick={remove}><b>⌫</b><span>삭제</span></button></aside>
   <div className={`fabric-workspace ${grid?"show-grid":""}`}>{doc.pages.map((page,index)=><div key={page.id} id={`fabric-page-${page.id}`} className={`fabric-page-card ${page.id===pageId?"is-active":""}`} onMouseDown={()=>setActivePage(page.id)}><div className="fabric-page-label">{index+1} PAGE · {page.width}×{page.height}</div><CanvasPage page={page} grid={grid} onReady={(id,r)=>{if(r)runtime.current[id]=r;else delete runtime.current[id]}} onChange={updatePageJson} onSelect={(v)=>{setInspector(v);if(v)setActivePage(v.pageId)}} onThumb={(id,url)=>setThumbs(x=>({...x,[id]:url}))}/></div>)}</div>
   <aside className="fabric-inspector"><h3>{selected?`${kind} 설정`:"요소 설정"}</h3>{selected?<><label>X<input type="number" value={Math.round(selected.left||0)} onChange={e=>setProp("left",Number(e.target.value))}/></label><label>Y<input type="number" value={Math.round(selected.top||0)} onChange={e=>setProp("top",Number(e.target.value))}/></label><label>회전<input type="number" value={Math.round(selected.angle||0)} onChange={e=>setProp("angle",Number(e.target.value))}/></label><label>투명도<input type="range" min="0" max="1" step="0.05" value={selected.opacity??1} onChange={e=>setProp("opacity",Number(e.target.value))}/></label>{kind==="text"&&<><label>글자 크기<input type="number" min="8" max="200" value={selected.fontSize||32} onChange={e=>setProp("fontSize",Number(e.target.value))}/></label><label>글자색<input type="color" value={String(selected.fill||"#3d2b20")} onChange={e=>setProp("fill",e.target.value)}/></label><label>정렬<select value={selected.textAlign||"left"} onChange={e=>setProp("textAlign",e.target.value)}><option value="left">왼쪽</option><option value="center">가운데</option><option value="right">오른쪽</option></select></label></>}{["rect","hline","vline"].includes(kind)&&<><label>색상<input type="color" value={String(selected.fill||"#6c625c")} onChange={e=>setProp("fill",e.target.value)}/></label>{kind==="rect"&&<><label>선 색상<input type="color" value={String(selected.stroke||"#6c625c")} onChange={e=>setProp("stroke",e.target.value)}/></label><label>선 굵기<input type="number" min="0" max="30" value={selected.strokeWidth||0} onChange={e=>setProp("strokeWidth",Number(e.target.value))}/></label></>}</>}</>:<p>캔버스에서 요소를 선택하세요.</p>}<div className="fabric-layer-actions"><button type="button" onClick={()=>layer("front")}>맨 앞으로</button><button type="button" onClick={()=>layer("forward")}>앞으로</button><button type="button" onClick={()=>layer("backward")}>뒤로</button><button type="button" onClick={()=>layer("back")}>맨 뒤로</button></div></aside>
  </div>
  <footer className="fabric-pages-bar"><div className="fabric-thumbs">{doc.pages.map((p,i)=><button type="button" key={p.id} className={p.id===pageId?"is-active":""} onClick={()=>{setActivePage(p.id);document.getElementById(`fabric-page-${p.id}`)?.scrollIntoView({behavior:"smooth",block:"center"})}}>{thumbs[p.id]?<img src={thumbs[p.id]} alt=""/>:<span>{i+1}</span>}<small>{i+1}</small></button>)}</div><div className="fabric-page-buttons"><button type="button" onClick={addPage}>+ 페이지 추가</button><button type="button" onClick={dupPage}>페이지 복제</button><button type="button" onClick={()=>movePage(-1)}>← 순서</button><button type="button" onClick={()=>movePage(1)}>순서 →</button><button type="button" onClick={deletePage}>페이지 삭제</button></div></footer>
 </section>
}

function GuideOverlay({page,guide}:{page:FabricPage;guide:GuideState}){return <div className="fabric-guide-overlay" aria-hidden="true">{guide.x.map((x,i)=><i key={`x${i}`} className="fabric-guide-x" style={{left:`${x/page.width*100}%`}}/>)}{guide.y.map((y,i)=><i key={`y${i}`} className="fabric-guide-y" style={{top:`${y/page.height*100}%`}}/>)}{guide.distances&&<><b className="fabric-distance d-left">{guide.distances.left}px</b><b className="fabric-distance d-right">{guide.distances.right}px</b><b className="fabric-distance d-top">{guide.distances.top}px</b><b className="fabric-distance d-bottom">{guide.distances.bottom}px</b></>}</div>}
