"use client";

import type { GalleryTags } from "@/lib/gallery-tags";
import { rollbackUploadedMedia, uploadGalleryDataImages } from "@/lib/r2-media-client";
export type GalleryAnalysis={caption:string;space:string[];styles:string[];colors:string[];materials:string[];features:string[];keywords:string[];model?:string;analyzedAt?:string};
export type GalleryItem={id:string;src:string;title:string;projectSlug?:string;projectTitle?:string;searchText?:string;analysis?:GalleryAnalysis;tags?:GalleryTags;createdAt:string};
const KEY="fengshui-gallery-v2";const LEGACY_KEY="fengshui-gallery-v1";export const GALLERY_EVENT="fengshui-gallery-updated";
function normalize(items:GalleryItem[]){return [...items].sort((a,b)=>(Date.parse(b.createdAt)||0)-(Date.parse(a.createdAt)||0))}
export function readGalleryItems():GalleryItem[]{if(typeof window==="undefined")return[];try{const raw=window.localStorage.getItem(KEY)||window.localStorage.getItem(LEGACY_KEY)||"[]";return normalize(JSON.parse(raw) as GalleryItem[])}catch{return[]}}
function cache(items:GalleryItem[]){if(typeof window==="undefined")return;window.localStorage.setItem(KEY,JSON.stringify(normalize(items)));window.dispatchEvent(new CustomEvent(GALLERY_EVENT))}
export async function fetchGalleryItems(admin=false):Promise<GalleryItem[]>{try{const r=await fetch(admin?"/api/admin/gallery":"/api/gallery",{credentials:admin?"include":"same-origin",cache:"no-store"});const d=await r.json().catch(()=>null) as {ok?:boolean;items?:GalleryItem[]}|null;if(!r.ok||!d?.ok||!Array.isArray(d.items))throw new Error();if(admin&&d.items.length===0){const legacy=readGalleryItems();if(legacy.length){const migrated=await saveGalleryItemsToServer(legacy);cache(migrated);return migrated}}cache(d.items);return normalize(d.items)}catch{return readGalleryItems()}}
export async function saveGalleryItemsToServer(items:GalleryItem[]):Promise<GalleryItem[]>{const uploadedUrls:string[]=[];try{const uploaded=await uploadGalleryDataImages(items,uploadedUrls);const r=await fetch("/api/admin/gallery",{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify({items:uploaded})});const d=await r.json().catch(()=>null) as {ok?:boolean;items?:GalleryItem[];error?:string}|null;if(!r.ok||!d?.ok||!Array.isArray(d.items))throw new Error(d?.error||"갤러리 서버 저장에 실패했습니다.");return d.items}catch(error){await rollbackUploadedMedia(uploadedUrls);throw error}}
export async function addGalleryItems(items:Array<Omit<GalleryItem,"id"|"createdAt">&{id?:string}>){const t=Date.now();const prepared:GalleryItem[]=items.map((item,index)=>({...item,id:item.id||crypto.randomUUID(),createdAt:new Date(t+index).toISOString()}));const stored=await saveGalleryItemsToServer(prepared);cache([...stored,...readGalleryItems().filter(old=>!stored.some(n=>n.id===old.id))]);return stored}
export async function deleteGalleryItem(id:string){const r=await fetch("/api/admin/gallery",{method:"DELETE",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify({id})});if(!r.ok)throw new Error("갤러리 서버 삭제에 실패했습니다.");cache(readGalleryItems().filter(item=>item.id!==id))}
const HIDDEN_KEY="fengshui-gallery-hidden-v1";export function readHiddenGalleryIds():string[]{if(typeof window==="undefined")return[];try{return JSON.parse(window.localStorage.getItem(HIDDEN_KEY)||"[]") as string[]}catch{return[]}}
export function hideGalleryItem(id:string){const next=Array.from(new Set([...readHiddenGalleryIds(),id]));window.localStorage.setItem(HIDDEN_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent(GALLERY_EVENT))}
