"use client";

import Image from "next/image";
import { DragEvent, useEffect, useMemo, useRef, useState } from "react";
import { addGalleryItems, fetchGalleryItems, GALLERY_CLIENT_VERSION, GALLERY_EVENT, probeR2, readGalleryItems, type GalleryItem } from "@/lib/gallery-store";
import { optimizeImageFile } from "@/lib/image-optimizer";
import { showAdminToast } from "@/lib/admin-toast";
import { EMPTY_GALLERY_TAGS, GALLERY_TAG_OPTIONS, galleryTagsToSearchText, type GalleryTags } from "@/lib/gallery-tags";
import styles from "./GalleryManagerV7.module.css";

const MAX_BATCH = 10;
const OPTIMIZE_CONCURRENCY = 2;
type UploadStatus = "queued" | "optimizing" | "ready" | "failed";
type UploadTask = { id:string; fileName:string; src:string; status:UploadStatus; tags:GalleryTags; error?:string };
type MultiTagKey = Exclude<keyof GalleryTags,"space">;

const cloneTags=(tags:GalleryTags):GalleryTags=>({space:tags.space,structures:[...tags.structures],styles:[...tags.styles],colors:[...tags.colors],materials:[...tags.materials],features:[...tags.features]});
const statusText=(status:UploadStatus)=>({queued:"대기",optimizing:"이미지 최적화 중",ready:"태그 확인 필요",failed:"처리 실패"} as const)[status];
async function runPool<T>(items:T[],limit:number,worker:(item:T,index:number)=>Promise<void>){let cursor=0;async function runner(){while(cursor<items.length){const index=cursor++;await worker(items[index],index)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>runner()))}

function UploadIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M4 7.5A2.5 2.5 0 0 1 6.5 5h2l1.2-1.5h4.6L15.5 5h2A2.5 2.5 0 0 1 20 7.5v9A2.5 2.5 0 0 1 17.5 19h-11A2.5 2.5 0 0 1 4 16.5z"/><circle cx="12" cy="12" r="3.2"/></svg>}
function CloseIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17"/></svg>}
function TrashIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg>}
function ChevronIcon({open}:{open:boolean}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={{transform:open?"rotate(180deg)":"none"}}><path d="m7 10 5 5 5-5"/></svg>}
function FolderIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.55" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3.5 7.5h6l1.8 2H20.5v8.5A2 2 0 0 1 18.5 20h-13a2 2 0 0 1-2-2z"/><path d="M3.5 7.5V6A2 2 0 0 1 5.5 4h4l1.8 2H18a2 2 0 0 1 2 2v1.5"/></svg>}

function TagGroup({title,options,selected,single=false,onToggle}:{title:string;options:readonly string[];selected:string[];single?:boolean;onToggle:(value:string)=>void}){return <fieldset className={styles.tagGroup}><legend className={styles.tagLegend}>{title}{single&&<small>필수 1개</small>}</legend><div className={styles.tagButtons}>{options.map(option=><button key={option} type="button" className={`${styles.tagButton} ${selected.includes(option)?styles.selected:""}`} aria-pressed={selected.includes(option)} onClick={()=>onToggle(option)}>{option}</button>)}</div></fieldset>}
function TagEditor({tags,onChange}:{tags:GalleryTags;onChange:(tags:GalleryTags)=>void}){const toggleSpace=(value:string)=>onChange({...tags,space:tags.space===value?"":value});const toggleMulti=(key:MultiTagKey,value:string)=>{const values=tags[key];onChange({...tags,[key]:values.includes(value)?values.filter(item=>item!==value):[...values,value]})};return <div className={styles.tagEditor}><TagGroup title="공간" options={GALLERY_TAG_OPTIONS.spaces} selected={tags.space?[tags.space]:[]} single onToggle={toggleSpace}/><TagGroup title="구조" options={GALLERY_TAG_OPTIONS.structures} selected={tags.structures} onToggle={v=>toggleMulti("structures",v)}/><TagGroup title="스타일" options={GALLERY_TAG_OPTIONS.styles} selected={tags.styles} onToggle={v=>toggleMulti("styles",v)}/><TagGroup title="색상" options={GALLERY_TAG_OPTIONS.colors} selected={tags.colors} onToggle={v=>toggleMulti("colors",v)}/><TagGroup title="소재" options={GALLERY_TAG_OPTIONS.materials} selected={tags.materials} onToggle={v=>toggleMulti("materials",v)}/><TagGroup title="특징" options={GALLERY_TAG_OPTIONS.features} selected={tags.features} onToggle={v=>toggleMulti("features",v)}/></div>}

export default function GalleryManager(){
 const [items,setItems]=useState<GalleryItem[]>([]);const [r2Status,setR2Status]=useState<"checking"|"ok"|"error">("checking");const [r2Message,setR2Message]=useState("R2 연결 확인 중");const [tasks,setTasks]=useState<UploadTask[]>([]);const [sortOrder,setSortOrder]=useState<"latest"|"oldest">("latest");const [processing,setProcessing]=useState(false);const [commonTags,setCommonTags]=useState<GalleryTags>(()=>cloneTags(EMPTY_GALLERY_TAGS));const [editingTaskId,setEditingTaskId]=useState<string|null>(null);const [commonOpen,setCommonOpen]=useState(false);const [dragging,setDragging]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
 const sync=()=>setItems(readGalleryItems());useEffect(()=>{sync();void fetchGalleryItems(true).then(setItems).catch(error=>{setR2Status("error");setR2Message(error instanceof Error?error.message:"서버 연결 실패");showAdminToast(error instanceof Error?error.message:"서버 연결 실패","error")});void probeR2().then(result=>{setR2Status("ok");setR2Message(result.message)}).catch(error=>{setR2Status("error");setR2Message(error instanceof Error?error.message:"R2 연결 확인 실패")});window.addEventListener(GALLERY_EVENT,sync);return()=>window.removeEventListener(GALLERY_EVENT,sync)},[]);
 const readyTasks=useMemo(()=>tasks.filter(task=>task.status==="ready"&&task.src),[tasks]);const sortedItems=useMemo(()=>[...items].sort((a,b)=>sortOrder==="latest"?b.createdAt.localeCompare(a.createdAt):a.createdAt.localeCompare(b.createdAt)),[items,sortOrder]);const confirmedCount=readyTasks.filter(task=>task.tags.space).length;const missingCount=readyTasks.length-confirmedCount;
 const patchTask=(id:string,patch:Partial<UploadTask>)=>setTasks(current=>current.map(task=>task.id===id?{...task,...patch}:task));
 const onFiles=async(files?:FileList|null)=>{const selected=Array.from(files||[]).filter(file=>file.type.startsWith("image/"));if(!selected.length)return;if(selected.length>MAX_BATCH){showAdminToast(`한 번에 최대 ${MAX_BATCH}장까지 선택할 수 있습니다.`,"error");return}const nextTasks:UploadTask[]=selected.map(file=>({id:crypto.randomUUID(),fileName:file.name.replace(/\.[^.]+$/, ""),src:"",status:"queued",tags:cloneTags(EMPTY_GALLERY_TAGS)}));setTasks(nextTasks);setEditingTaskId(null);setCommonTags(cloneTags(EMPTY_GALLERY_TAGS));setCommonOpen(false);setProcessing(true);try{await runPool(selected.map((file,index)=>({file,task:nextTasks[index]})),OPTIMIZE_CONCURRENCY,async({file,task})=>{patchTask(task.id,{status:"optimizing",error:undefined});try{const optimized=await optimizeImageFile(file,{maxWidth:2400,maxHeight:3200,quality:.90});if(items.some(item=>item.src===optimized)){patchTask(task.id,{status:"failed",error:"이미 등록된 동일한 이미지입니다."});return}patchTask(task.id,{src:optimized,status:"ready"})}catch(error){patchTask(task.id,{status:"failed",error:error instanceof Error?error.message:"이미지를 처리하지 못했습니다."})}});showAdminToast(`${selected.length}장의 이미지 준비가 끝났습니다. 태그를 선택해 주세요.`)}finally{setProcessing(false);if(inputRef.current)inputRef.current.value=""}};
 const onDrop=(event:DragEvent<HTMLLabelElement>)=>{event.preventDefault();setDragging(false);if(!processing)void onFiles(event.dataTransfer.files)};
 const applyCommonTags=()=>{if(!readyTasks.length)return;setTasks(current=>current.map(task=>task.status==="ready"?{...task,tags:cloneTags(commonTags)}:task));showAdminToast(`${readyTasks.length}장에 공통 태그를 적용했습니다.`)};
 const removeTask=(id:string)=>{setTasks(current=>current.filter(task=>task.id!==id));if(editingTaskId===id)setEditingTaskId(null)};
 const saveAll=async()=>{if(!readyTasks.length)return showAdminToast("저장할 사진이 없습니다.","error");if(missingCount>0){setEditingTaskId(readyTasks.find(task=>!task.tags.space)?.id||null);return showAdminToast(`공간 태그가 없는 사진이 ${missingCount}장 있습니다.`,"error")}setProcessing(true);try{await addGalleryItems(readyTasks.map(task=>({id:task.id,src:task.src,title:task.fileName||"인테리어 이미지",tags:cloneTags(task.tags),searchText:[task.fileName,galleryTagsToSearchText(task.tags)].filter(Boolean).join(" ")})));setTasks([]);setEditingTaskId(null);setCommonTags(cloneTags(EMPTY_GALLERY_TAGS));setCommonOpen(false);showAdminToast(`${readyTasks.length}장이 R2에 저장되었습니다.`)}catch(error){showAdminToast(error instanceof Error?error.message:"갤러리 저장에 실패했습니다.","error")}finally{setProcessing(false)}};
 return <div className={styles.shell}>
  <section className={styles.panel}>
   <header className={styles.header}><div><h1>GALLERY 관리</h1><p>사진을 선택하고 태그를 지정한 후 저장합니다.</p><p style={{marginTop:6,fontSize:12,fontWeight:700}}>{r2Status==="ok"?"● ":r2Status==="error"?"⚠ ":"○ "}{r2Message} · 클라이언트 v{GALLERY_CLIENT_VERSION}</p></div><div className={styles.headerActions}><a className={styles.headerDeleteButton} href="/gallery/?adminDelete=1&returnTo=%2Fadmin%2Fgallery"><span className={styles.buttonIcon}><TrashIcon/></span>홈페이지에서 이미지 삭제</a><button type="button" className={styles.headerSaveButton} disabled={!readyTasks.length||processing||r2Status!=="ok"} onClick={saveAll}>{processing?"처리 중…":"저장"}</button></div></header>
   <div className={styles.body}>
    <label className={`${styles.uploadZone} ${dragging?styles.isDragging:""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop}>
     <input ref={inputRef} type="file" accept="image/*" multiple disabled={processing} onChange={event=>void onFiles(event.target.files)}/><span><span className={styles.uploadIcon}><UploadIcon/></span><strong className={styles.uploadTitle}>{processing?"이미지를 준비하는 중입니다…":"파일 선택"}</strong><small className={styles.uploadHelp}>이미지 한 번에 최대 10장 · 원본 비율 유지<br/>클릭하거나 사진을 이곳으로 끌어오세요.</small></span>
    </label>
    {readyTasks.length>0&&<section className={styles.section}><div className={styles.sectionBar}><div className={styles.sectionTitle}><h2>공통 태그</h2><p>선택한 사진에 동일한 태그를 적용합니다.</p></div><button type="button" className={styles.pillButton} onClick={()=>setCommonOpen(open=>!open)}>태그 선택 <span className={styles.buttonIcon}><ChevronIcon open={commonOpen}/></span></button></div>{commonOpen&&<div className={styles.commonPanel}><TagEditor tags={commonTags} onChange={setCommonTags}/><div className={styles.actions}><button type="button" className={styles.darkButton} onClick={applyCommonTags}>전체 {readyTasks.length}장에 적용</button></div></div>}</section>}
    {tasks.length>0&&<section className={styles.section}><div className={styles.sectionTitle}><h2>사진 미리보기</h2><p>각 사진의 공간 태그를 확인한 뒤 저장하세요.</p></div><div className={styles.previewGrid}>{tasks.map((task,index)=>{const isEditing=editingTaskId===task.id;const selectedTags=[task.tags.space,...task.tags.structures,...task.tags.styles,...task.tags.colors,...task.tags.materials,...task.tags.features].filter(Boolean);return <article className={styles.previewCard} key={task.id}><div className={styles.imageWrap}>{task.src?<Image src={task.src} alt={task.fileName} width={480} height={560} unoptimized/>:<span className={styles.imagePlaceholder}>{task.status==="optimizing"?"최적화 중":"대기"}</span>}<span className={styles.indexBadge}>{index+1}</span><button type="button" className={styles.removeButton} onClick={()=>removeTask(task.id)} aria-label={`${task.fileName} 선택 해제`}><CloseIcon/></button></div><div className={styles.cardBody}><strong className={styles.fileName}>{task.fileName}</strong><span className={styles.status}>{task.status==="ready"&&task.tags.space?"태그 확정":statusText(task.status)}</span>{selectedTags.length>0&&<div className={styles.selectedTags}>{selectedTags.slice(0,8).map(tag=><span className={styles.tagChip} key={tag}>{tag}</span>)}</div>}{task.error&&<small className={styles.warning}>{task.error}</small>}{task.status==="ready"&&<div className={styles.cardActions}><button type="button" onClick={()=>setEditingTaskId(isEditing?null:task.id)}>{isEditing?"태그 닫기":task.tags.space?"태그 수정":"태그 선택"}</button></div>}</div>{isEditing&&<div className={styles.individualEditor}><TagEditor tags={task.tags} onChange={tags=>patchTask(task.id,{tags})}/></div>}</article>})}</div><div className={styles.summary}><span>{confirmedCount}장 태그 확정</span>{missingCount>0&&<strong>{missingCount}장 공간 태그 필요</strong>}</div></section>}
   </div>
  </section>
  <section className={styles.panel}><div className={styles.registeredHeader}><div className={styles.registeredTitle}><h2>등록된 GALLERY</h2><span className={styles.count}>{items.length}장</span></div><div className={styles.registeredActions}><a className={styles.selectedDeleteButton} href="/gallery/?adminDelete=1&returnTo=%2Fadmin%2Fgallery"><span className={styles.buttonIcon}><TrashIcon/></span>선택 이미지 삭제</a><label className={styles.sortSelect}><span className={styles.srOnly}>정렬</span><select value={sortOrder} onChange={event=>setSortOrder(event.target.value as "latest"|"oldest")}><option value="latest">최신순</option><option value="oldest">오래된순</option></select><span className={styles.buttonIcon}><ChevronIcon open={false}/></span></label></div></div>{items.length===0?<div className={styles.empty}><span className={styles.emptyIcon}><FolderIcon/></span><strong>아직 등록된 이미지가 없습니다.</strong><p>위에서 이미지를 업로드해 주세요.</p></div>:<div className={styles.registeredGrid}>{sortedItems.map(item=><article className={styles.registeredCard} key={item.id}><Image src={item.src} alt={item.title} width={360} height={420} unoptimized/><div className={styles.registeredMeta}><strong>{item.title}</strong>{item.tags?.space&&<span>{[item.tags.space,...item.tags.styles,...item.tags.colors].slice(0,5).join(" · ")}</span>}<a href="/gallery/?adminDelete=1&returnTo=%2Fadmin%2Fgallery">이미지 삭제</a></div></article>)}</div>}</section>
 </div>
}
